# Generated by Django 2.1.2 on 2018-10-23 08:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('answers_title', models.CharField(max_length=30)),
                ('answers_text', models.CharField(max_length=300)),
                ('date_of_creation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('questions_title', models.CharField(max_length=30)),
                ('questions_text', models.CharField(max_length=300)),
                ('date_of_creation', models.DateTimeField()),
                ('asker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.ExtraUser')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='teller_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.ExtraUser'),
        ),
    ]
