# Generated by Django 2.1.2 on 2018-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181023_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smth',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('string', models.CharField(max_length=30)),
            ],
        ),
    ]
