# Generated by Django 2.1.2 on 2018-10-27 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181027_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_creation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 11, 51, 27, 279748)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_creation',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 11, 51, 27, 279092)),
        ),
    ]
